name: Generate Documentation

concurrency:
  group: gen-docs
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "3 * * * *"
  

jobs:
  deploy:
    name: Generate-Docs
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/truecharts/devcontainer:v2.5.0@sha256:a2f259a3fb1e8e529d1a3dcdbd9d244384183a78cdeb41d2fcf13f948c98abba
    steps:
      - name: Install Kubernetes tools
        uses: yokawasa/action-setup-kube-tools@f7f73d7965074b0f5491b7210ff51e3254d42058 # tag=v0.8.2
        with:
          setup-tools: |
            helmv3
          helm: "3.8.0"

      - name: Prep Helm
        run: |
          helm repo add truecharts https://charts.truecharts.org
          helm repo add truecharts-library https://library-charts.truecharts.org
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add metallb https://metallb.github.io/metallb
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add prometheus https://prometheus-community.github.io/helm-charts
          helm repo update
    
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        name: Checkout
        with:
          fetch-depth: 1
          token: ${{ secrets.BOT_TOKEN }}

      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        with:
          repository: truecharts/apps
          path: charts
          fetch-depth: 1
          token: ${{ secrets.BOT_TOKEN }}
          
      - name: Security Scan
        shell: bash
        run: |
          helm_dep() {
              helm dependency update "${1}" --skip-refresh || (sleep 10 && helm dependency update "${1}" --skip-refresh) || (sleep 10 && helm dependency update "${1}" --skip-refresh)
              }
          export -f helm_dep
          
          scan_prep() {
              local chart="$1"
              local chartname="$(basename ${chart})"
              local train="$(basename $(dirname "${chart}"))"
              echo "Preparing security scans for: ${chartname}"
              mkdir -p ${chart}/render
              rm -rf docs/charts/${train}/${chartname}/security.md || echo "removing old security.md file failed..."
              cat charts/templates/security.tpl >> docs/charts/${train}/${chartname}/security.md
              echo "" >> docs/charts/${train}/${chartname}/security.md
              helm template ${chart} --output-dir ${chart}/render > /dev/null || (  echo "helm templating failed..." && return 1 )
              }
           export -f scan_prep
           
          helm_sec_scan() {
              local chart="$1"
              local chartname="$(basename ${chart})"
              local train="$(basename $(dirname "${chart}"))"
              trivy config -f template --template "@./charts/templates/trivy-config.tpl" -o ${chart}/render/tmpsec${chartname}.md ${chart}/render
              rm -rf ${chart}/render/tmpsec${chartname}.md || true
              echo "" >> docs/charts/${train}/${chartname}/security.md
              }
           export -f helm_sec_scan
           
          container_sec_scan() {
              local chart="$1"
              local chartname="$(basename ${chart})"
              local train="$(basename $(dirname "${chart}"))"
              echo "Scanning container security for ${chartname}"
              echo "## Containers" >> docs/charts/${train}/${chartname}/security.md
              echo "" >> docs/charts/${train}/${chartname}/security.md
              echo "### Detected Containers" >> docs/charts/${train}/${chartname}/security.md
              echo "" >> docs/charts/${train}/${chartname}/security.md
              find ./${chart}/render/ -name '*.yaml' -type f -exec cat {} \; | grep image: | sed "s/image: //g" | sed "s/\"//g" >> ${chart}/render/containers.tmp
              cat ${chart}/render/containers.tmp >> docs/charts/${train}/${chartname}/security.md
              echo "" >> docs/charts/${train}/${chartname}/security.md
              echo "### Scan Results" >> docs/charts/${train}/${chartname}/security.md
              echo "" >> docs/charts/${train}/${chartname}/security.md
              for container in $(cat ${chart}/render/containers.tmp); do
                echo "processing container: ${container}"
                echo "" >> docs/charts/${train}/${chartname}/security.md
                trivy image -f template --template "@./charts/templates/trivy-container.tpl" -o ${chart}/render/tmpsec${chartname}.md "${container}"
                cat ${chart}/render/tmpsec${chartname}.md >> docs/charts/${train}/${chartname}/security.md
                rm -rf ${chart}/render/tmpsec${chartname}.md || true
                echo "" >> docs/charts/${train}/${chartname}/security.md
              done
              }
           export -f container_sec_scan
          finish_sec() {
              local chart="$1"
              local chartname="$(basename ${chart})"
              local train="$(basename $(dirname "${chart}"))"
              sed -i 's;<br>;<br />;g' docs/charts/${train}/${chartname}/security.md
              }
           export -f finish_sec
           
          run_scans() {
              local chart="$1"
              local chartname="$(basename ${chart})"
              helm_dep ${chart}
              scan_prep ${chart} || (  echo "Security prep failed..." && return 0 )
              helm_sec_scan ${chart} || (  echo "Helm Security Scan failed..." && return 0 )
              container_sec_scan ${chart} || (  echo "Container Security Scan failed..." && return 0 )
              finish_sec ${chart} || (  echo "Container Security Scan failed..." && return 0 )
              }
           export -f run_scans
           
           
          parthreads=$(($(nproc) * 2))
          parallel -j ${parthreads} run_scans '2>&1' ::: charts/charts/**/*
           
      - name: Create commit
        uses: stefanzweifel/git-auto-commit-action@49620cd3ed21ee620a48530e81dba0d139c9cb80 # tag=v4
        with:
          file_pattern: docs/charts/**/
          commit_message: "chore: Auto-update chart docs"
          commit_user_name: truecharts-bot
          commit_user_email: bot@truecharts.org
          commit_author: truecharts-bot <bot@truecharts.org>
